repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Organiza los imports con isort
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: check-todos  # Verifica que no haya TODOs sin resolver
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas
      - id: end-of-file-fixer  # Asegura que haya una línea en blanco al final de cada archivo

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2  # Última versión estable (verifica si hay una más reciente)
    hooks:
      - id: bandit
        name: Análisis de Seguridad con Bandit
        entry: bandit -ll  # Escanea recursivamente con nivel de log detallado
        language: python
        types: [python]
