version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: empleo
    ports:
      - "5431:5432"
    volumes:
      - database_adapted:/var/lib/postgresql/data

  adapted-work:
    image: adapted-work:0.0.1
    env_file:
      - .env
    ports:
      - "8032:8000"

volumes:
  database_adapted:
